library(shiny)
library(ggplot2)
library(tidyr)
library(leaflet)
library(vroom)
library(dplyr)
library(styler)
library(RColorBrewer)
library(rsconnect)
library(stringr)

source("app_ui.R")
source("app_server.R")
source("datasets.R")
# Creates shiny application using "ui" and "server"
shinyApp(ui = ui, server = server)
